window:
  decorations: buttonless

  padding:
    x: 8
    y: 8

  startup_mode: Maximized

font:
  normal:
    family: Ubuntu Mono

  size: 14

draw_bold_text_with_bright_colors: true

#import:
  #- ~/.dotfiles/alacritty/senior_mars.yml

env:
  TERM: xterm-256color
